export const english = {
  addWorker: 'Add Worker',
  addHouse: 'Add House',
  workerClass: 'Worker class',
  capacity: 'Capacity',
  house: 'House',
  worker: 'Worker',
  houses: 'Houses',
  workers: 'Workers',
  noOption: 'No option',
  free: 'Free',
  averageDailyProfit: 'Average daily profit',
  strategy: 'Strategy',
  homepage: 'Homepage',
  changeGender: 'Change gender',
  changeEmblem: 'Change emblem',
  changeRarity: 'Change rarity',
  in: 'in',
  noHouse: 'No House',
  noWorker: 'No Worker',
  feedback: 'Feedback',
  developedBy: 'Developed by',
}
