export const portuguese = {
  addWorker: 'Adicionar Trabalhador',
  addHouse: 'Adicionar Casa',
  workerClass: 'Classe do Trabalhador',
  capacity: 'Capacidade',
  house: 'Casa',
  worker: 'Trabalhador',
  houses: 'Casas',
  workers: 'Trabalhadores',
  noOption: 'Sem opção',
  free: 'Grátis',
  averageDailyProfit: 'Lucro médio diário',
  strategy: 'Estratégia',
  homepage: 'Homepage',
  changeGender: 'Mudar gênero',
  changeEmblem: 'Mudar emblema',
  changeRarity: 'Mudar raridade',
  in: 'em',
  noHouse: 'Nenhuma Casa',
  noWorker: 'Nenhum Trabalhador',
  feedback: 'Feedback',
  developedBy: 'Desenvolvido por',
}
