export const spanish = {
  addWorker: 'Añadir trabajador',
  addHouse: 'Añadir Casa',
  workerClass: 'Tipo de trabajador',
  capacity: 'Capacidad',
  house: 'Casa',
  worker: 'Trabajador',
  houses: 'Casas',
  workers: 'Trabajadores',
  noOption: 'Sin opción',
  free: 'Gratis',
  averageDailyProfit: 'Ganancia medio diario',
  strategy: 'Estrategia',
  homepage: 'Homepage',
  changeGender: 'Cambiar de genero',
  changeEmblem: 'Cambiar emblema',
  changeRarity: 'Cambiar rareza',
  in: 'en',
  noHouse: 'Ninguna Casa',
  noWorker: 'Ningún Trabajador',
  feedback: 'Feedback',
  developedBy: 'Desarrollado por',
}
