import { enumEmblems, rarities, workerClasses } from './constants'

const workerDictionary = Object.freeze({
  [workerClasses.bandit]: { rarity: rarities.common, workingReward: 24, workingHours: 6, emblem: enumEmblems.villain },
  [workerClasses.villager]: {
    rarity: rarities.common,
    workingReward: 48,
    workingHours: 12,
    emblem: enumEmblems.citizen,
  },
  [workerClasses.innKeeper]: {
    rarity: rarities.common,
    workingReward: 96,
    workingHours: 24,
    emblem: enumEmblems.citizen,
  },
  [workerClasses.young]: { rarity: rarities.common, workingReward: 144, workingHours: 36, emblem: enumEmblems.citizen },
  [workerClasses.pirate]: {
    rarity: rarities.common,
    workingReward: 192,
    workingHours: 48,
    emblem: enumEmblems.villain,
  },
  [workerClasses.old]: { rarity: rarities.common, workingReward: 288, workingHours: 72, emblem: enumEmblems.citizen },
  [workerClasses.blacksmith]: {
    rarity: rarities.uncommon,
    workingReward: 48,
    workingHours: 8,
    emblem: enumEmblems.protector,
  },
  [workerClasses.miner]: { rarity: rarities.uncommon, workingReward: 72, workingHours: 12, emblem: enumEmblems.union },
  [workerClasses.fisherman]: {
    rarity: rarities.uncommon,
    workingReward: 108,
    workingHours: 18,
    emblem: enumEmblems.union,
  },
  [workerClasses.builder]: {
    rarity: rarities.uncommon,
    workingReward: 144,
    workingHours: 24,
    emblem: enumEmblems.union,
  },
  [workerClasses.farmer]: {
    rarity: rarities.uncommon,
    workingReward: 288,
    workingHours: 48,
    emblem: enumEmblems.union,
  },
  [workerClasses.adventurer]: {
    rarity: rarities.uncommon,
    workingReward: 432,
    workingHours: 72,
    emblem: enumEmblems.protector,
  },
  [workerClasses.banditLeader]: {
    rarity: rarities.rare,
    workingReward: 64,
    workingHours: 8,
    emblem: enumEmblems.villain,
  },
  [workerClasses.bard]: { rarity: rarities.rare, workingReward: 96, workingHours: 12, emblem: enumEmblems.citizen },
  [workerClasses.dancer]: { rarity: rarities.rare, workingReward: 192, workingHours: 24, emblem: enumEmblems.union },
  [workerClasses.mage]: { rarity: rarities.rare, workingReward: 384, workingHours: 48, emblem: enumEmblems.enchanter },
  [workerClasses.archer]: {
    rarity: rarities.rare,
    workingReward: 576,
    workingHours: 72,
    emblem: enumEmblems.protector,
  },
  [workerClasses.gladiator]: {
    rarity: rarities.epic,
    workingReward: 216,
    workingHours: 24,
    emblem: enumEmblems.protector,
  },
  [workerClasses.priestess]: {
    rarity: rarities.epic,
    workingReward: 360,
    workingHours: 36,
    emblem: enumEmblems.enchanter,
  },
  [workerClasses.pirateLeader]: {
    rarity: rarities.epic,
    workingReward: 792,
    workingHours: 72,
    emblem: enumEmblems.villain,
  },
  [workerClasses.ninja]: { rarity: rarities.epic, workingReward: 96, workingHours: 8, emblem: enumEmblems.exile },
  [workerClasses.cult]: { rarity: rarities.epic, workingReward: 624, workingHours: 48, emblem: enumEmblems.exile },
  [workerClasses.alchemist]: {
    rarity: rarities.unique,
    workingReward: 336,
    workingHours: 24,
    emblem: enumEmblems.enchanter,
  },
  [workerClasses.royalGuard]: {
    rarity: rarities.unique,
    workingReward: 720,
    workingHours: 48,
    emblem: enumEmblems.warrior,
  },
  [workerClasses.knight]: {
    rarity: rarities.unique,
    workingReward: 192,
    workingHours: 12,
    emblem: enumEmblems.warrior,
  },
  [workerClasses.thief]: { rarity: rarities.unique, workingReward: 102, workingHours: 6, emblem: enumEmblems.exile },
  [workerClasses.rogue]: { rarity: rarities.unique, workingReward: 432, workingHours: 24, emblem: enumEmblems.exile },
  [workerClasses.paladin]: {
    rarity: rarities.unique,
    workingReward: 864,
    workingHours: 48,
    emblem: enumEmblems.warrior,
  },
  [workerClasses.santaClaus]: {
    rarity: rarities.unique,
    workingReward: 1368,
    workingHours: 72,
    emblem: enumEmblems.noEmblem,
  },
  [workerClasses.necromancer]: {
    rarity: rarities.legendary,
    workingReward: 480,
    workingHours: 24,
    emblem: enumEmblems.enchanter,
  },
  [workerClasses.plagueDoctor]: {
    rarity: rarities.legendary,
    workingReward: 252,
    workingHours: 12,
    emblem: enumEmblems.warrior,
  },
  [workerClasses.prince]: {
    rarity: rarities.legendary,
    workingReward: 1056,
    workingHours: 48,
    emblem: enumEmblems.royal,
  },
  [workerClasses.princess]: {
    rarity: rarities.legendary,
    workingReward: 1104,
    workingHours: 48,
    emblem: enumEmblems.royal,
  },
  [workerClasses.king]: { rarity: rarities.legendary, workingReward: 624, workingHours: 24, emblem: enumEmblems.royal },
  [workerClasses.queen]: {
    rarity: rarities.legendary,
    workingReward: 672,
    workingHours: 24,
    emblem: enumEmblems.royal,
  },
})

export const getWorkerMetadata = (workerClass) => ({ ...workerDictionary[workerClass] })
