import { enumEmblems, rarities, workerClasses } from './constants'

export const workerMetadata = Object.freeze({
  [workerClasses.bandit]: {
    rarity: rarities.common,
    workingReward: 24,
    workingHours: 6,
    emblem: enumEmblems.villain,
    image: 'sprites/bandit_gender.png',
  },
  [workerClasses.villager]: {
    rarity: rarities.common,
    workingReward: 48,
    workingHours: 12,
    emblem: enumEmblems.citizen,
    image: 'sprites/villager_female.png',
  },
  [workerClasses.innKeeper]: {
    rarity: rarities.common,
    workingReward: 96,
    workingHours: 24,
    emblem: enumEmblems.citizen,
    image: 'sprites/innkeeper_male.png',
  },
  [workerClasses.young]: {
    rarity: rarities.common,
    workingReward: 144,
    workingHours: 36,
    emblem: enumEmblems.citizen,
    image: 'sprites/young_gender.png',
  },
  [workerClasses.pirate]: {
    rarity: rarities.common,
    workingReward: 192,
    workingHours: 48,
    emblem: enumEmblems.villain,
    image: 'sprites/pirate_gender.png',
  },
  [workerClasses.old]: {
    rarity: rarities.common,
    workingReward: 288,
    workingHours: 72,
    emblem: enumEmblems.citizen,
    image: 'sprites/old_gender.png',
  },
  [workerClasses.blacksmith]: {
    rarity: rarities.uncommon,
    workingReward: 48,
    workingHours: 8,
    emblem: enumEmblems.protector,
    image: 'sprites/lumberjack_male.png',
  },
  [workerClasses.miner]: {
    rarity: rarities.uncommon,
    workingReward: 72,
    workingHours: 12,
    emblem: enumEmblems.union,
    image: 'sprites/miner_male.png',
  },
  [workerClasses.fisherman]: {
    rarity: rarities.uncommon,
    workingReward: 108,
    workingHours: 18,
    emblem: enumEmblems.union,
    image: 'sprites/fisherman_male.png',
  },
  [workerClasses.builder]: {
    rarity: rarities.uncommon,
    workingReward: 144,
    workingHours: 24,
    emblem: enumEmblems.union,
    image: 'sprites/builder_male.png',
  },
  [workerClasses.farmer]: {
    rarity: rarities.uncommon,
    workingReward: 288,
    workingHours: 48,
    emblem: enumEmblems.union,
    image: 'sprites/farmer_male.png',
  },
  [workerClasses.adventurer]: {
    rarity: rarities.uncommon,
    workingReward: 432,
    workingHours: 72,
    emblem: enumEmblems.protector,
    image: 'sprites/adventurer_gender.png',
  },
  [workerClasses.banditLeader]: {
    rarity: rarities.rare,
    workingReward: 64,
    workingHours: 8,
    emblem: enumEmblems.villain,
    image: 'sprites/banditleader_male.png',
  },
  [workerClasses.bard]: {
    rarity: rarities.rare,
    workingReward: 96,
    workingHours: 12,
    emblem: enumEmblems.citizen,
    image: 'sprites/bard_female.png',
  },
  [workerClasses.dancer]: {
    rarity: rarities.rare,
    workingReward: 192,
    workingHours: 24,
    emblem: enumEmblems.union,
    image: 'sprites/dancer_female.png',
  },
  [workerClasses.mage]: {
    rarity: rarities.rare,
    workingReward: 384,
    workingHours: 48,
    emblem: enumEmblems.enchanter,
    image: 'sprites/mage_gender.png',
  },
  [workerClasses.archer]: {
    rarity: rarities.rare,
    workingReward: 576,
    workingHours: 72,
    emblem: enumEmblems.protector,
    image: 'sprites/archer_female.png',
  },
  [workerClasses.gladiator]: {
    rarity: rarities.epic,
    workingReward: 216,
    workingHours: 24,
    emblem: enumEmblems.protector,
    image: 'sprites/gladiator_male.png',
  },
  [workerClasses.priestess]: {
    rarity: rarities.epic,
    workingReward: 360,
    workingHours: 36,
    emblem: enumEmblems.enchanter,
    image: 'sprites/priestess_female.png',
  },
  [workerClasses.pirateLeader]: {
    rarity: rarities.epic,
    workingReward: 792,
    workingHours: 72,
    emblem: enumEmblems.villain,
    image: 'sprites/pirateleader_male.png',
  },
  [workerClasses.ninja]: {
    rarity: rarities.epic,
    workingReward: 96,
    workingHours: 8,
    emblem: enumEmblems.exile,
    image: 'sprites/ninja_gender.png',
  },
  [workerClasses.cult]: {
    rarity: rarities.epic,
    workingReward: 624,
    workingHours: 48,
    emblem: enumEmblems.exile,
    image: 'sprites/cult_gender.png',
  },
  [workerClasses.alchemist]: {
    rarity: rarities.unique,
    workingReward: 336,
    workingHours: 24,
    emblem: enumEmblems.enchanter,
    image: 'sprites/alchemist_gender.png',
  },
  [workerClasses.royalGuard]: {
    rarity: rarities.unique,
    workingReward: 720,
    workingHours: 48,
    emblem: enumEmblems.warrior,
    image: 'sprites/royalguard_gender.png',
  },
  [workerClasses.knight]: {
    rarity: rarities.unique,
    workingReward: 192,
    workingHours: 12,
    emblem: enumEmblems.warrior,
    image: 'sprites/knight_female.png',
  },
  [workerClasses.thief]: {
    rarity: rarities.unique,
    workingReward: 102,
    workingHours: 6,
    emblem: enumEmblems.exile,
    image: 'sprites/thief_female.png',
  },
  [workerClasses.rogue]: {
    rarity: rarities.unique,
    workingReward: 432,
    workingHours: 24,
    emblem: enumEmblems.exile,
    image: 'sprites/rogue_male.png',
  },
  /* [workerClasses.paladin]: {
    rarity: rarities.unique,
    workingReward: 864,
    workingHours: 48,
    emblem: enumEmblems.warrior,
    image: 'sprites/paladin_gender.png',
  }, */
  [workerClasses.santaClaus]: {
    rarity: rarities.unique,
    workingReward: 1368,
    workingHours: 72,
    emblem: enumEmblems.noEmblem,
    image: 'sprites/santaclous_male.png',
  },
  [workerClasses.necromancer]: {
    rarity: rarities.legendary,
    workingReward: 480,
    workingHours: 24,
    emblem: enumEmblems.enchanter,
    image: 'sprites/necromancer_male.png',
  },
  [workerClasses.plagueDoctor]: {
    rarity: rarities.legendary,
    workingReward: 252,
    workingHours: 12,
    emblem: enumEmblems.warrior,
    image: 'sprites/plaguedoctor_female.png',
  },
  [workerClasses.prince]: {
    rarity: rarities.legendary,
    workingReward: 1056,
    workingHours: 48,
    emblem: enumEmblems.royal,
    image: 'sprites/prince_male.png',
  },
  [workerClasses.princess]: {
    rarity: rarities.legendary,
    workingReward: 1104,
    workingHours: 48,
    emblem: enumEmblems.royal,
    image: 'sprites/princess_female.png',
  },
  [workerClasses.king]: {
    rarity: rarities.legendary,
    workingReward: 624,
    workingHours: 24,
    emblem: enumEmblems.royal,
    image: 'sprites/king_male.png',
  },
  [workerClasses.queen]: {
    rarity: rarities.legendary,
    workingReward: 672,
    workingHours: 24,
    emblem: enumEmblems.royal,
    image: 'sprites/queen_female.png',
  },
})
